### ISSUE TITLE
IntelliJ

### ISSUE THREAD

**Issue by 3nigm4** [jesse-c/ayu-jetbrains#3]
Hello! I can't get this to work with intelliJ! There is a colors folder in ".IntelliJIdea2017.3\config\colors", but it does not accept .xml and // Settings: Editor > Color Scheme // ~click_wheel~ // "Import Scheme", says not a valid eclipse color scheme ...

**Comment by maqdev** [comment]
@3nigm4 it's not in eclipse format. You may import `ayu-mirage.xml` as Intellij Color format and it works, no need to copy manually.

**Comment by maqdev** [comment]
Or in a command line copy XML to `~/Library/Preferences/IntelliJIdea2017.3/settingsRepository/repository/colors/Ayu-mirage.icls`

**Comment by martin-spa** [comment]
E.g. on my side, for IntelliJ Community 2017.3. 

1. I had to set the file in: ~/.IdeaIC2017.3/**config/**colors and named the extension from .xml to .icls.
2. Restart IntelliJ.
3. Then just went to Settings > Editor > Color Scheme and it was available in the drop-down.

**Comment by jesse-c** [comment]
Thanks for the input guys. I've updated the README to hopefully be a little more helpful (including a link to the official documentation). I'm going to go ahead and close this for now.
